### ISSUE TITLE
为什么用 docker search 搜索不到？

### ISSUE THREAD

**Issue by wanglongbiao** [jenkins-zh/docker-zh#36]
我用 `docker search jenkins` 搜索的时候，能搜索到 `docker.io/amazeeio/jenkins-slave` 这种镜像，却搜索不到 `docker.io/jenkinszh/jenkins-zh ` 
只能 `docker search jenkins-zh` 这样才能找到，这是为啥？

**Comment by LinuxSuRen** [comment]
应该是 docker hub 的排序规则影响的，没有被排到前面。

**Comment by wanglongbiao** [comment]
但是一些 star 为 0 的也能搜到，docker hub 这么不可靠啊

**Comment by LinuxSuRen** [comment]
也不一定，可以了解下他们的排序规则

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："王龙彪 "<notifications@github.com&gt;;
发送时间：2020年5月12日(星期二) 上午9:46
收件人："jenkins-zh/jenkins-formulas" <jenkins-formulas@noreply.github.com&gt;;
抄送："Zhao Xiaojie "<rick@jenkins-zh.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [jenkins-zh/jenkins-formulas] 为什么用 docker search 搜索不到？ (#36)
-----------------------------------

 

 
但是一些 star 为 0 的也能搜到，docker hub 这么不可靠啊

**Comment by wanglongbiao** [comment]
好的，我去看看，谢谢啊
