### ISSUE TITLE
Grammatical error in Readme file. 

### ISSUE THREAD

**Issue by ArslanYM** [jenkins-zh/docker-zh#62]
![grammatical errors](https://user-images.githubusercontent.com/104521101/230637076-88a4bfc4-750d-4b10-84ec-ec9aede8e471.png)

It should say : 
"We greatly appreciate any and all contributions."

I would love to fix this.

**Comment by LinuxSuRen** [comment]
hi @ArslanYM Thanks for that and please go ahead.
